//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZABIST_IR_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAllocateCoursesDetail
    {
        public int tAllocateDetailID { get; set; }
        public Nullable<int> tAllocateID { get; set; }
        public Nullable<decimal> Course_Id { get; set; }
        public string sCourse_Code { get; set; }
        public string sCourse_LongDesc { get; set; }
        public string Instructor { get; set; }
        public string userID { get; set; }
        public string Class { get; set; }
        public Nullable<decimal> iSemester_Id { get; set; }
        public Nullable<byte> iSemesterSection_Id { get; set; }
        public Nullable<byte> tCampus_Id { get; set; }
        public Nullable<byte> tProgram_Id { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> isChecked { get; set; }
        public Nullable<bool> isCheckedByIR { get; set; }
        public Nullable<bool> isCopyAvailable { get; set; }
    }
}
