//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZABIST_IR_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssessmentResultDetail
    {
        public int tAResultDID { get; set; }
        public Nullable<int> tAResultID { get; set; }
        public Nullable<int> StandardID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> GradePoint { get; set; }
    }
}
