//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZABIST_IR_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssessmentResult
    {
        public int tAResultID { get; set; }
        public Nullable<int> tAllocateID { get; set; }
        public Nullable<int> tAllocateDetailID { get; set; }
        public string CourseID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Remarks { get; set; }
        public string RemarksIR { get; set; }
        public string CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
