//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZABIST_IR_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCampu
    {
        public byte tCampus_Id { get; set; }
        public string sCampus_ShortDesc { get; set; }
        public string sCampus_LongDesc { get; set; }
        public byte tCity_Id { get; set; }
        public string sCreatedBy { get; set; }
        public string sModifiedBy { get; set; }
        public System.DateTime xLastModifiedDate { get; set; }
        public string ConrollerLtrGrd { get; set; }
        public string AssConrollerLtrGrd { get; set; }
        public string dbConnectionString { get; set; }
        public string zabDeskURL { get; set; }
    }
}
