//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZABIST_IR_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vu_CampustoStandard
    {
        public string semster { get; set; }
        public string searchyear { get; set; }
        public Nullable<decimal> SCore1 { get; set; }
        public string campusname { get; set; }
        public string StandardDescription { get; set; }
    }
}
